interface Region {
  en: string;
  ru: string;
  "uz-cyr": string;
  uz: string;
}

export const regions: Region[] = [
  { en: "Angrеn", ru: "Ангрен", "uz-cyr": "Ангрен", uz: "Angrеn" },
  { en: "Andijon", ru: "Андижан", "uz-cyr": "Андижон", uz: "Andijon" },
  { en: "Arnasoy", ru: "Арнасой", "uz-cyr": "Арнасой", uz: "Arnasoy" },
  {
    en: "Ashxabod",
    ru: "Ашхабад",
    "uz-cyr": "Ашхабод",
    uz: "Ashxabod",
  },
  { en: "Bеkobod", ru: "Бекабад", "uz-cyr": "Бекобод", uz: "Bеkobod" },
  { en: "Bishkеk", ru: "Бишкек", "uz-cyr": "Бишкек", uz: "Bishkеk" },
  { en: "Boysun", ru: "Байсун", "uz-cyr": "Бойсун", uz: "Boysun" },
  {
    en: "Buloqboshi",
    ru: "Булакбаши",
    "uz-cyr": "Булоқбоши",
    uz: "Buloqboshi",
  },
  {
    en: "Burchmulla",
    ru: "Бурчмулла",
    "uz-cyr": "Бурчмулла",
    uz: "Burchmulla",
  },
  { en: "Buxoro", ru: "Бухара", "uz-cyr": "Бухоро", uz: "Buxoro" },
  { en: "Gazli", ru: "Газли", "uz-cyr": "Газли", uz: "Gazli" },
  {
    en: "Gallaorol",
    ru: "Галлаорал",
    "uz-cyr": "Ғаллаорол",
    uz: "Gallaorol",
  },
  { en: "Guzor", ru: "Гузор", "uz-cyr": "Ғузор", uz: "Guzor" },
  {
    en: "Guliston",
    ru: "Гулистан",
    "uz-cyr": "Гулистон",
    uz: "Guliston",
  },
  { en: "Dеnov", ru: "Денау", "uz-cyr": "Денов", uz: "Dеnov" },
  {
    en: "Dеhqonobod",
    ru: "Дехканабад",
    "uz-cyr": "Деҳқонобод",
    uz: "Dеhqonobod",
  },
  {
    en: "Jalolobod",
    ru: "Джалалабад",
    "uz-cyr": "Жалолобод",
    uz: "Jalolobod",
  },
  { en: "Jambul", ru: "Джамбул", "uz-cyr": "Жамбул", uz: "Jambul" },
  { en: "Jambay", ru: "Джамбай", "uz-cyr": "Жомбой", uz: "Jambay" },
  { en: "Dostlik", ru: "Дустлик", "uz-cyr": "Дўстлик", uz: "Dostlik" },
  {
    en: "Dushanbe",
    ru: "Душанбе",
    "uz-cyr": "Душанбе",
    uz: "Dushanbe",
  },
  { en: "Zamin", ru: "Замин", "uz-cyr": "Зомин", uz: "Zamin" },
  {
    en: "Zarafshon",
    ru: "Зарафшан",
    "uz-cyr": "Зарафшон",
    uz: "Zarafshon",
  },
  {
    en: "Kanibadam",
    ru: "Канибадам",
    "uz-cyr": "Канибодом",
    uz: "Kanibadam",
  },
  { en: "Kanimex", ru: "Канимех", "uz-cyr": "Конимех", uz: "Kanimex" },
  {
    en: "Karavulbazar",
    ru: "Каравулбазар",
    "uz-cyr": "Каровулбозор",
    uz: "Karavulbazar",
  },
  { en: "Karakul", ru: "Каракул", "uz-cyr": "Қоракўл", uz: "Karakul" },
  { en: "Karshi", ru: "Карши", "uz-cyr": "Қарши", uz: "Karshi" },
  { en: "Kasany", ru: "Касан", "uz-cyr": "Касаны", uz: "Kasany" },
  {
    en: "Kattepan",
    ru: "Каттепан",
    "uz-cyr": "Каттепон",
    uz: "Kattepan",
  },
  { en: "Kitob", ru: "Китаб", "uz-cyr": "Китоб", uz: "Kitob" },
  { en: "Kogon", ru: "Когон", "uz-cyr": "Кўғон", uz: "Kogon" },
  { en: "Kurshab", ru: "Куршаб", "uz-cyr": "Қуршаб", uz: "Kurshab" },
  { en: "Kyzylsu", ru: "Кызылсу", "uz-cyr": "Қизилсу", uz: "Kyzylsu" },
  {
    en: "Mingechaur",
    ru: "Мингечаур",
    "uz-cyr": "Мингачаур",
    uz: "Mingechaur",
  },
  {
    en: "Namangan",
    ru: "Наманган",
    "uz-cyr": "Наманган",
    uz: "Namangan",
  },
  { en: "Narakol", ru: "Наракол", "uz-cyr": "Наракўл", uz: "Narakol" },
  { en: "Navoi", ru: "Навои", "uz-cyr": "Навоий", uz: "Navoi" },
  { en: "Nurota", ru: "Нурота", "uz-cyr": "Нурота", uz: "Nurota" },
  {
    en: "Oltinkol",
    ru: "Олтинкўл",
    "uz-cyr": "Олтинкўл",
    uz: "Oltinkol",
  },
  { en: "Osh", ru: "Ош", "uz-cyr": "Ош", uz: "Osh" },
  {
    en: "Paxtakor",
    ru: "Пахтакор",
    "uz-cyr": "Паҳтакор",
    uz: "Paxtakor",
  },
  {
    en: "Pakhtaabad",
    ru: "Пахтаабад",
    "uz-cyr": "Паҳтаобод",
    uz: "Pakhtaabad",
  },
  {
    en: "Penjikent",
    ru: "Пенжикент",
    "uz-cyr": "Панҷикент",
    uz: "Penjikent",
  },
  { en: "Piskent", ru: "Пискент", "uz-cyr": "Пискент", uz: "Piskent" },
  { en: "Pop", ru: "Поп", "uz-cyr": "Поп", uz: "Pop" },
  { en: "Qoqon", ru: "Коканд", "uz-cyr": "Қўқон", uz: "Qoqon" },
  {
    en: "Qo`rg`ontepa",
    ru: "Кургантепа",
    "uz-cyr": "Қўғонтепа",
    uz: "Qo`rg`ontepa",
  },
  { en: "Qungrad", ru: "Кунград", "uz-cyr": "Қунғрад", uz: "Qungrad" },
  { en: "Ravnaki", ru: "Равнаки", "uz-cyr": "Равнаки", uz: "Ravnaki" },
  { en: "Reka", ru: "Река", "uz-cyr": "Река", uz: "Reka" },
  { en: "Sarband", ru: "Сарбанд", "uz-cyr": "Сарбанд", uz: "Sarband" },
  {
    en: "Saryag`och",
    ru: "Сарыагач",
    "uz-cyr": "Сарйогоч",
    uz: "Saryag`och",
  },
  {
    en: "Shakhrinav",
    ru: "Шахринав",
    "uz-cyr": "Шаҳринав",
    uz: "Shakhrinav",
  },
  {
    en: "Shahrisabz",
    ru: "Шахрисабз",
    "uz-cyr": "Шаҳрисабз",
    uz: "Shahrisabz",
  },
  {
    en: "Shahrisabz",
    ru: "Шахрисабз",
    "uz-cyr": "Шаҳрисабз",
    uz: "Shahrisabz",
  },
  {
    en: "Shayxontohur",
    ru: "Шайхантахур",
    "uz-cyr": "Шайхонтоҳур",
    uz: "Shayxontohur",
  },
  {
    en: "Shurachinskiy",
    ru: "Шурочинский",
    "uz-cyr": "Шурашинский",
    uz: "Shurachinskiy",
  },
  {
    en: "Syrdarya",
    ru: "Сырдарья",
    "uz-cyr": "Сирдарё",
    uz: "Syrdarya",
  },
  {
    en: "Toshkent",
    ru: "Ташкент",
    "uz-cyr": "Тошкент",
    uz: "Toshkent",
  },
  {
    en: "Tashkent",
    ru: "Ташкент",
    "uz-cyr": "Тошкент",
    uz: "Toshkent",
  },
  {
    en: "Tashkent city",
    ru: "Ташкент город",
    "uz-cyr": "Тошкент шаҳар",
    uz: "Tashkent city",
  },
  { en: "Tеrmiz", ru: "Термез", "uz-cyr": "Тирмиз", uz: "Tеrmiz" },
  {
    en: "Uchquduq",
    ru: "Учкудук",
    "uz-cyr": "Учқудуқ",
    uz: "Uchquduq",
  },
  {
    en: "Farg`ona",
    ru: "Фергана",
    "uz-cyr": "Фарғона",
    uz: "Farg`ona",
  },
  { en: "Furqat", ru: "Фуркат", "uz-cyr": "Фурқат", uz: "Furqat" },
  {
    en: "Khanabad",
    ru: "Ханабад",
    "uz-cyr": "Хонобод",
    uz: "Khanabad",
  },
  { en: "Chirchiq", ru: "Чирчик", "uz-cyr": "Чирчик", uz: "Chirchiq" },
  {
    en: "Shohimardon",
    ru: "Шахимардан",
    "uz-cyr": "Шаҳимардон",
    uz: "Shohimardon",
  },
  {
    en: "Shohimardon",
    ru: "Шахимардан",
    "uz-cyr": "Шаҳимардон",
    uz: "Shohimardon",
  },
  {
    en: "Shofirkon",
    ru: "Шафиркон",
    "uz-cyr": "Шофиркон",
    uz: "Shofirkon",
  },
  {
    en: "Sharafkhan",
    ru: "Шарафхан",
    "uz-cyr": "Шарофхон",
    uz: "Sharafkhan",
  },
  {
    en: "Sherobod",
    ru: "Шерабад",
    "uz-cyr": "Шеробод",
    uz: "Sherobod",
  },
  {
    en: "Sherobod",
    ru: "Шерабад",
    "uz-cyr": "Шеробод",
    uz: "Sherobod",
  },
  {
    en: "Sherobod",
    ru: "Шерабад",
    "uz-cyr": "Шеробод",
    uz: "Sherobod",
  },
  {
    en: "Sherobod",
    ru: "Шерабад",
    "uz-cyr": "Шеробод",
    uz: "Sherobod",
  },
  { en: "Yangiyul", ru: "Янгиюль", "uz-cyr": "Янгиюл", uz: "Yangiyul" },
  { en: "Yangiyul", ru: "Янгиюль", "uz-cyr": "Янгиюл", uz: "Yangiyul" },
];
